[project]
name = "caiman"
description = "Library and software for ROI detection and deconvolution of Calcium Imaging datasets"
authors = [
	{ name = "Andrea Giovannucci"},
	{ name = "Eftychios Pnevmatikakis"},
	{ name = "Johannes Friedrich" },
	{ name = "Valentina Staneva" },
	{ name = "Ben Deverett" },
	{ name = "Erick Cobos" },
	{ name = "Jeremie Kalfon"}]
readme = "README.md"

[build-system]
requires = ["cython", "distutils", "numpy", "setuptools", "wheel"]

[tool.setuptools]
py-modules = ["buildhelper_cython"]

[tool.setuptools.cmdclass]
build_py = "buildhelper_cython.build_py"
