name: Multi-OS and Python Version Test

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: caiman

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda install pip
          pip install -e .
          caimanmanager install --inplace

      - name: Test
        shell: bash -l {0}
        run: |
          caimanmanager test
